sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_takeout
    username: root
    password: 750825

  alioss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    access-key-id: xxx
    access-key-secret: xxx
    bucket-name: sky-takeout-clementine
